.comp AllocationType {
  //----------------------------------------------------------------------------
  // "Input"/declared rules
  //
  // https://souffle-lang.github.io/components#input-rules
  //----------------------------------------------------------------------------

  .decl alloc_subregion_type(?region: AllocSubregion, ?type: Type) inline
  .decl backpropagated_allocation_type(?alloc: Allocation, ?type: Type) inline
  .decl sig_allocation_type(?alloc: Allocation, ?type: Type) inline
  .decl heap_allocation_by_alloc_exc(?insn: Instruction, ?heapAlloc: HeapAllocation) inline

  //----------------------------------------------------------------------------
  // "Output"/defined rules
  //----------------------------------------------------------------------------

  .decl allocation_type(?alloc:Allocation, ?type:Type)

  allocation_type(?alloc, ?type) :-
    static_allocation_type(?alloc, ?type).

  allocation_type(?alloc, ?type) :-
    alloc_subregion_type(?alloc, ?type).

  allocation_type(?alloc, ?type) :-
    backpropagated_allocation_type(?alloc, ?type).

  allocation_type(?alloc, ?type) :-
    sig_allocation_type(?alloc, ?type).
}
