.comp AtExit {
  //----------------------------------------------------------------------------
  // "Input"/declared rules
  //
  // https://souffle-lang.github.io/components#input-rules
  //----------------------------------------------------------------------------

  .decl alloc_aliases(?alloc1: Allocation, ?alloc2: Allocation) inline
  .decl reachable_callgraph_edge(?calleeCtx: Context, ?callee: FunctionDecl, ?callerCtx: Context, ?callerInstr: CallBase) inline
  .decl operand_points_to(?aCtx: Context, ?alloc: Allocation, ?ctx: Context, ?operand: Operand) inline
  .decl reachable_context(?ctx: Context, ?func: FunctionDecl) inline

  //----------------------------------------------------------------------------
  // "Output"/defined rules
  //
  // NOTE! This component can compute new points-to facts, and these need to be
  // propagated back into the points-to component.
  //----------------------------------------------------------------------------

  // The following rule augments the logic about identifying funcs
  // registered to run at program exit, so that it also works with
  // func pointers.

  .decl _registers_atexit(?callerCtx: Context, ?funcOp: Operand)

  _registers_atexit(?callerCtx, ?funcOp) :-
    func_name(?atExit, "@atexit"),
    reachable_callgraph_edge(_, ?atExit, ?callerCtx, ?callerInstr),
    actual_arg(?callerInstr, 0, ?funcOp).

  // Functions registered to @atexit are also reachable if the @atexit
  // call is reachable.
  .decl called_at_exit(func:FunctionDecl)

  called_at_exit(?callback) :-
    _registers_atexit(?ctx, ?funcOp),
    operand_points_to(_, ?alloc, ?ctx, ?funcOp),
    func_by_location(?alloc, ?callback).

  called_at_exit(Callback) :-
    func_name(AtExit, "@atexit"),
    reachable_callgraph_edge(_, AtExit, _, CallerInstr),
    call_instr_arg(CallerInstr, 0, Constant),
    // the following is a simplified version of logic that can only
    // work with direct func calls
    constant_references_func(Constant, Callback).

}
